### ISSUE TITLE
Unable to run Blame Trait

### ISSUE THREAD

**Issue by Aaarrrgggh** [ceeram/blame#11]
Hi,

thanks for your trait.

I tried to install it in my application, with the last Cakephp3 beta, but I dit not manage to run it. 
The options 'loggedInUser' in the BlameDBehavior is empty. Code in function beforeSave is not runned.

Someone can help ?

Thanks!

**Comment by ceeram** [comment]
Did you also add the trait in your controller as described in the readme?
Op 15 jan. 2015 08:35 schreef "Aaarrrgggh" <notifications@github.com>:

**Comment by Aaarrrgggh** [comment]
Yes, I added the trait in my AppController.php

I tried to debug LoggedInUserListener.php and BlameTrait.php but the script does enter neither in the loadModel function nor in the beforeSave function.

I think something is missing, but I don't see what ?!

**Comment by ceeram** [comment]
I can have a look at it later and see if i can reproduce.
Op 15 jan. 2015 10:16 schreef "Aaarrrgggh" <notifications@github.com>:

**Comment by Aaarrrgggh** [comment]
okay, thanks !

I will also make new tests tonight.

**Comment by Aaarrrgggh** [comment]
I confirm that the script does enter neither in the loadModel function nor in the beforeSave function. 

I added Plugin::load('Ceeram/Blame'); in bootstrap.php,
I put use \Ceeram\Blame\Controller\BlameTrait in my AppController.php,
added $this->addBehavior('Ceeram/Blame.Blame'); in my model (the script goes into the function beforeSave(), but nothing else is executed)

What's wrong ?!

Thanks !

**Comment by ceeram** [comment]
I am not able to reproduce this, everything works fine for me.
Perhaps drop by on #cakephp channel on irc to get support

**Comment by ceeram** [comment]
here is my appcontroller file:

https://gist.github.com/ceeram/ba0ef0e17b16dfe78d8a

note that you need to have both line 18 and 31

**Comment by justinatack** [comment]
I know this is a closed issue but reading this help fixed the same issue I was having.

I couldn't work out why this Blame Trait wasn't working. It wasn't until I looked at your AppController and saw that I needed to put

use BlameTrait in the Class that it started working.

Can you update your docs for noobies like me? I can do a pull request if it helps.
